# Generated by Django 5.1.5 on 2025-01-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediconnect_api', '0002_hospital_mapurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='mapurl',
            field=models.URLField(blank=True, help_text='Google Maps embed URL'),
        ),
    ]
