# Generated by Django 5.1.5 on 2025-01-24 17:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediconnect_api', '0007_alter_hospital_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='doctorprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Total years of experience'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_profiles/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('general', 'General Physician'), ('cardiologist', 'Cardiologist'), ('dermatologist', 'Dermatologist'), ('neurologist', 'Neurologist'), ('orthopedic', 'Orthopedic'), ('pediatrician', 'Pediatrician'), ('psychiatrist', 'Psychiatrist'), ('surgeon', 'Surgeon'), ('urologist', 'Urologist'), ('ophthalmologist', 'Ophthalmologist'), ('dentist', 'Dentist'), ('ent', 'ENT Specialist'), ('gynecologist', 'Gynecologist')], default='general', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='mediconnect_api.doctorservice'),
        ),
    ]
