# Generated by Django 5.1.5 on 2025-01-25 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediconnect_api', '0009_remove_doctorprofile_profile_picture_doctorcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorrating',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='doctorrating',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='mediconnect_api.doctorrating'),
        ),
        migrations.DeleteModel(
            name='DoctorComment',
        ),
    ]
